name: Count Lines of Code

on:
  schedule:
    - cron: '0 0 * * 0'   # 毎週日曜に自動更新
  workflow_dispatch:       # 手動実行も可能

jobs:
  count:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Install tools
        run: sudo apt-get install -y cloc jq gh

      - name: Authenticate gh
        run: gh auth login --with-token <<< "${{ secrets.PAT }}"

      - name: Clone all repos
        run: |
          mkdir repos && cd repos
          gh repo list 32Lwk --limit 200 --json name --jq '.[].name' | while read repo; do
            gh repo clone 32Lwk/$repo
          done

      - name: Count lines
        run: |
          cloc repos --json --out=lines.json
          jq '{ schemaVersion: 1, label: "total code lines", message: (.SUM.code|tostring), color: "blueviolet" }' lines.json > shield.json

      - name: Commit badge json
        run: |
          mv shield.json $GITHUB_WORKSPACE/
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add shield.json
          git commit -m "update code lines badge" || echo "no changes"
          git push
